account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile_view, name='edit_profile'),
]





core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from jobs import views as job_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls', namespace='account')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('', job_views.job_list, name='home'),
]


from django.contrib import admin
from django.urls import path, include
from jobs import views as job_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls', namespace='account')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('', job_views.job_list, name='home'),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls', namespace='account')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('', job_views.job_list, name='home'),
    path('apply/', include('applications.urls', namespace='applications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py


from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.job_list, name='job_list'),
    path('add/', views.add_job, name='add_job'),
    path('add_category/', views.add_category, name='add_category'),
    path('add_image/', views.add_image, name='add_image'),
    path('job/<int:job_id>/', views.job_detail, name='job_detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Job Hunter!!{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <a href="{% url 'jobs:job_list' %}" class="navbar-brand">Job Hunter</a>
            <ul class="navbar-nav">
                <li class="nav-item"><a href="{% url 'jobs:job_list' %}" class="nav-link">Job Listings</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'account:profile' %}" class="nav-link">Profile</a></li>
                    <li class="nav-item"><a href="{% url 'account:logout' %}" class="nav-link">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'account:login' %}" class="nav-link">Login</a></li>
                    <li class="nav-item"><a href="{% url 'account:register' %}" class="nav-link">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="content-wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <footer>
        <div class="footer-content">
            <div class="footer-section about">
                <h3>Job Hunter</h3>
                <p>Your one-stop solution for job hunting. Find the best job that fits your career and skill set.</p>
                <div class="contact">
                    <span><i class="fas fa-phone"></i> &nbsp; +123 456 789</span>
                    <span><i class="fas fa-envelope"></i> &nbsp; info@jobhunter.com</span>
                </div>
                <div class="socials">
                    <a href="#"><i class="fab fa-facebook"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/base.js' %}"></script>
</body>
</html>

templates/navigation.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Job Hunter</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'jobs-index' %}">Jobs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account-index' %}">Accounts</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    